import { Toaster } from "react-hot-toast";
import "../globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full w-full bg-shade-overlay">
      <body className="flex min-h-full min-w-full text-sm text-shade-pencil-black">
        <Toaster
          toastOptions={{
            style: {
              background: "#FFFFFF",
              fontWeight: "bolder",
              fontSize: "12px",
              borderRadius: "8px",
              width: "fit-content",
              maxWidth: "50%",
            },
          }}
        />
        {children}
      </body>
    </html>
  );
}
